// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: movie_cast_crew_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CastCrew struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Actors           []string `protobuf:"bytes,1,rep,name=actors,proto3" json:"actors,omitempty"`
	Writers          []string `protobuf:"bytes,2,rep,name=writers,proto3" json:"writers,omitempty"`
	Producers        []string `protobuf:"bytes,3,rep,name=producers,proto3" json:"producers,omitempty"`
	ProductionHouse  []string `protobuf:"bytes,4,rep,name=productionHouse,proto3" json:"productionHouse,omitempty"`
	MusicComposition []string `protobuf:"bytes,5,rep,name=musicComposition,proto3" json:"musicComposition,omitempty"`
}

func (x *CastCrew) Reset() {
	*x = CastCrew{}
	if protoimpl.UnsafeEnabled {
		mi := &file_movie_cast_crew_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CastCrew) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastCrew) ProtoMessage() {}

func (x *CastCrew) ProtoReflect() protoreflect.Message {
	mi := &file_movie_cast_crew_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastCrew.ProtoReflect.Descriptor instead.
func (*CastCrew) Descriptor() ([]byte, []int) {
	return file_movie_cast_crew_message_proto_rawDescGZIP(), []int{0}
}

func (x *CastCrew) GetActors() []string {
	if x != nil {
		return x.Actors
	}
	return nil
}

func (x *CastCrew) GetWriters() []string {
	if x != nil {
		return x.Writers
	}
	return nil
}

func (x *CastCrew) GetProducers() []string {
	if x != nil {
		return x.Producers
	}
	return nil
}

func (x *CastCrew) GetProductionHouse() []string {
	if x != nil {
		return x.ProductionHouse
	}
	return nil
}

func (x *CastCrew) GetMusicComposition() []string {
	if x != nil {
		return x.MusicComposition
	}
	return nil
}

var File_movie_cast_crew_message_proto protoreflect.FileDescriptor

var file_movie_cast_crew_message_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x63, 0x61, 0x73, 0x74, 0x5f, 0x63, 0x72, 0x65,
	0x77, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x16, 0x67, 0x6f, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e,
	0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x22, 0xb0, 0x01, 0x0a, 0x08, 0x43, 0x61, 0x73, 0x74,
	0x43, 0x72, 0x65, 0x77, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x77,
	0x72, 0x69, 0x74, 0x65, 0x72, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x65, 0x72, 0x73, 0x12, 0x28, 0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x12, 0x2a,
	0x0a, 0x10, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x10, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x43,
	0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x20, 0x0a, 0x16, 0x63, 0x6f,
	0x6d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x6c, 0x69, 0x62,
	0x72, 0x61, 0x72, 0x79, 0x50, 0x01, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_movie_cast_crew_message_proto_rawDescOnce sync.Once
	file_movie_cast_crew_message_proto_rawDescData = file_movie_cast_crew_message_proto_rawDesc
)

func file_movie_cast_crew_message_proto_rawDescGZIP() []byte {
	file_movie_cast_crew_message_proto_rawDescOnce.Do(func() {
		file_movie_cast_crew_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_movie_cast_crew_message_proto_rawDescData)
	})
	return file_movie_cast_crew_message_proto_rawDescData
}

var file_movie_cast_crew_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_movie_cast_crew_message_proto_goTypes = []interface{}{
	(*CastCrew)(nil), // 0: gosample.movie.library.CastCrew
}
var file_movie_cast_crew_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_movie_cast_crew_message_proto_init() }
func file_movie_cast_crew_message_proto_init() {
	if File_movie_cast_crew_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_movie_cast_crew_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CastCrew); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_movie_cast_crew_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_movie_cast_crew_message_proto_goTypes,
		DependencyIndexes: file_movie_cast_crew_message_proto_depIdxs,
		MessageInfos:      file_movie_cast_crew_message_proto_msgTypes,
	}.Build()
	File_movie_cast_crew_message_proto = out.File
	file_movie_cast_crew_message_proto_rawDesc = nil
	file_movie_cast_crew_message_proto_goTypes = nil
	file_movie_cast_crew_message_proto_depIdxs = nil
}
